#!/bin/bash

REPO=/home/ostkamp/mercurial/hello.repo

for i in 0 1 2 3 4
do
  export REV$i=`cd $REPO; hg log -r $i | grep changeset | cut -c 16-19 2>//dev/null`
done
export REV_my_hello=`cat /tmp/REV5.my-hello`
export REV_my_new_hello=`cat /tmp/REV5.my-new-hello`
export REV6_my_new_hello=`cat /tmp/REV6.my-new-hello`
export REV7_my_new_hello=`cat /tmp/REV7.my-new-hello`

FILE=$1
rm -f $FILE.tmp
echo "Fixing $FILE"
cp $FILE $FILE.tmp
perl -p -i -e "s#REV0#$REV0#" $FILE.tmp
perl -p -i -e "s#REV1#$REV1#" $FILE.tmp
perl -p -i -e "s#REV2#$REV2#" $FILE.tmp
perl -p -i -e "s#REV3#$REV3#" $FILE.tmp
perl -p -i -e "s#REV4#$REV4#" $FILE.tmp
perl -p -i -e "s#REV_my_hello#$REV_my_hello#" $FILE.tmp
perl -p -i -e "s#REV_my_new_hello#$REV_my_new_hello#" $FILE.tmp
perl -p -i -e "s#REV6_my_new_hello#$REV6_my_new_hello#" $FILE.tmp
perl -p -i -e "s#REV7_my_new_hello#$REV7_my_new_hello#" $FILE.tmp
