#!/bin/bash

hg clone https://bitbucket.org/facebook/remotefilelog remotefilelog
export PWD=`pwd`
echo '[extensions]' >> $HGRC
echo 'remotefilelog = $PWD/remotefilelog/remotefilelog' >> $HGRC
echo '[remotefilelog]' >> $HGRC
echo 'server = True' >> $HGRC
echo 'cachepath = $PWD/cachepath' >> $HGRC

hg init srcrepo
echo blah > srcrepo/foo
hg -R srcrepo add
hg -R srcrepo commit -m "added blah"
echo woop > srcrepo/bar
hg -R srcrepo add
hg -R srcrepo commit -m "added woop"

#$ name: clone
hg clone --shallow ssh://localhost//$PWD/srcrepo --remotecmd `which hg` targetrepo

#$ name: check-shallow
ls -a targetrepo/.hg/store/data
