FROM ubuntu:16.04
RUN apt-get update && apt-get install -y \
	build-essential \
	bzip2 \
	git \
	graphviz \
	inkscape \
	make \
	pgf \
	poppler-utils \
	python \
	python-dev \
	python-docutils \
	python-sphinx \
	rcs \
	texlive-latex-base \
	texlive-latex-extra \
	unzip \
	wget \
   && rm -rf /var/lib/apt/lists/*
RUN wget https://www.mercurial-scm.org/release/mercurial-4.0-rc.tar.gz
RUN tar -xf mercurial-4.0-rc.tar.gz
RUN cd mercurial-4.0-rc && make install
