#!/bin/bash

cat > hello.c <<EOF
int main()
{
    printf("hello world!\n");
}
EOF

cat > goodbye.c <<EOF
int main()
{
    printf("goodbye world!\n");
}
EOF

#$ name: init

hg init myproject

#$ name: ls

ls -l

#$ name: ls2

ls -al myproject

#$ name: cat
# ... edit edit edit ...
cat hello.c

#$ name:
cp hello.c myproject
cd myproject

#$ name: status
hg status

#$ name: add-single
hg add hello.c

#$ name: status-added
hg status

#$ name: diff
hg diff

#$ name: commit-added
hg commit -m 'Initial commit'

#$ name:
cp ../goodbye.c hello.c

#$ name: cat-change
# ... edit edit edit ...
cat hello.c

#$ name: changed-statusdiff
hg status
hg diff


#$ name: summary
hg summary

#$ name: add

cp ../hello.c .
cp ../goodbye.c .
hg add
hg status

#$ name: commit

hg commit -m 'Initial commit'
