#!/bin/bash

hg init a
cd a
echo hello > myfile
hg commit -A -m 'Initial commit'

#$ name: branches

hg tip
hg branches

#$ name: branch

hg branch

#$ name: create

hg branch foo
hg branch

#$ name: status

hg status
hg tip

#$ name: commit

echo 'hello again' >> myfile
hg commit -m 'Second commit'
hg tip
