#!/usr/bin/env python

import sys
import os
import subprocess

testtmp = os.getenv('TESTTMP')
hgrcpath = os.getenv('HGRCPATH')
args = ['ssh',
        sys.argv[1], #hostname
        'HGRCPATH=' + hgrcpath + ' ' + 'TESTTMP=' + testtmp + ' ' + sys.argv[2]
        ]

sys.exit(subprocess.call(args))
