#!/usr/bin/env python

import sys
import os

if len(sys.argv) < 2:
    sys.exit(1)

tests = sys.argv[1:]

for test in tests:
    if test == "nodocker":
        if 'RUNNING_INSIDE_DOCKER' in os.environ:
            print "skipped: test doesn't work inside docker"
            sys.exit(1)
