#!/bin/bash

#$ name: version

hg version

#$ name: help

hg help init

#$ name: clone

hg clone http://hg.serpentine.com/tutorial/hello

#$ name: ls

ls -l
ls hello

#$ name: ls-a

cd hello
ls -a

#$ name: log

hg log

#$ name: log-r

hg log -r 3
hg log -r ff5d7b70a2a9
hg log -r 1 -r 4

#$ name: log.range

hg log -r 2:4
